// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SWVUEL.Infrastructure.Contracts.Entities;

[Table("Starship")]
public partial class Starship
{
    [Key]
    public int id { get; set; }

    [StringLength(150)]
    public string name { get; set; }

    [StringLength(150)]
    public string model { get; set; }

    [StringLength(150)]
    public string manufacturer { get; set; }

    [StringLength(150)]
    public string cost_in_credits { get; set; }

    [StringLength(150)]
    public string length { get; set; }

    [StringLength(150)]
    public string crew { get; set; }

    [StringLength(150)]
    public string passengers { get; set; }

    [StringLength(150)]
    public string starship_class { get; set; }

    [StringLength(150)]
    public string url { get; set; }
}